version: '3'

services:
  consul-server-1:
    build:
      context: ./
      dockerfile: ./Dockerfile
    hostname: 'consul-server-1'
    privileged: true
    volumes:
      - ./server/default.json:/etc/consul.d/default.json
      - ./server/consul.service:/usr/lib/systemd/system/consul.service

  consul-agent-1:
    build:
      context: ./
      dockerfile: ./Dockerfile
    hostname: 'consul-agent-1'
    privileged: true
    volumes:
      - ./agent/default.json:/etc/consul.d/default.json
      - ./agent/consul.service:/usr/lib/systemd/system/consul.service
    links:
      - "consul-server-1"
